version: "3.8"

services:
  postgres:
    image: postgres:16.10
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: user-api
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: "postgres"
      DATABASE_PORT: 5432
      DATABASE_NAME: "test"
      COGNITO_CLIENT_ID: ${COGNITO_CLIENT_ID}
      COGNITO_USER_POOL_ID: ${COGNITO_USER_POOL_ID}
      LOG_LEVEL: "info"
    ports:
      - "3000:3000"

volumes:
  postgres_data:
